### ISSUE TITLE
Error initialization

### ISSUE THREAD

**Issue by spawnax** [stffart/mopidy-yandexmusic#2]
ERROR    2023-02-08 23:59:29,729 [213:MainThread] mopidy.commands
  Got un-handled exception from YaMusicBackend
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 248, in _actor_error_handling
    yield
  File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 412, in start_backends
    backend = backend_class.start(
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 91, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mopidy_yamusic/backend.py", line 22, in __init__
    client = yandex_music.Client.from_credentials(username=login, password=password)
  File "/usr/local/lib/python3.9/dist-packages/yandex_music/client.py", line 206, in from_credentials
    token = cls(*args, **kwargs).generate_token_by_username_and_password(
  File "/usr/local/lib/python3.9/dist-packages/yandex_music/client.py", line 72, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yandex_music/client.py", line 279, in generate_token_by_username_and_password
    result = self._request.post(url, data, timeout=timeout, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yandex_music/utils/request.py", line 264, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.9/dist-packages/yandex_music/utils/request.py", line 215, in _request_wrapper
    raise BadRequest(message)
yandex_music.exceptions.BadRequest: invalid_grant login or password is not valid

**Comment by spawnax** [comment]
также после этой ошибки не открывается ссылка :6680/yamusic
выдаёт:
404: Not Found
